# Generated by Django 4.2.3 on 2023-09-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_endorsement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endorsement',
        ),
    ]
