# Generated by Django 4.2.3 on 2023-09-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='skill.jpg', null=True, upload_to=''),
        ),
    ]
