# Generated by Django 4.2.5 on 2023-10-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_language_project_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
