# Generated by Django 4.2.5 on 2023-11-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_language_delete_programminglanguage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
    ]
