# Generated by Django 4.2.5 on 2023-11-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
