# Generated by Django 4.2.5 on 2023-11-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_project_live_website_project_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='Skill_image.png', null=True, upload_to=''),
        ),
    ]
