# Generated by Django 4.2.5 on 2023-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
