# Generated by Django 4.2.5 on 2023-11-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='Skill_image.png', null=True, upload_to=''),
        ),
    ]
